/*
 * This file was automatically generated by EvoSuite
 * Thu May 14 19:29:04 GMT 2026
 */

package org.Model.Music;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.Model.Music.Music;
import org.junit.runner.RunWith;

public class Music_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Music music0 = new Music();
      music0.setLyrics((String) null);
      music0.play();
      assertEquals(1, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Music music0 = new Music("?KIafDq'(AZ(wv\"5b2", "", "?KIafDq'(AZ(wv\"5b2", "", "", "JyAjR2+]<3S`Hkf?i,0", (String) null, 2390, false);
      boolean boolean0 = music0.isExplicit();
      assertEquals(0, music0.getReproductions());
      assertFalse(boolean0);
      assertEquals("?KIafDq'(AZ(wv\"5b2", music0.getPublisher());
      assertEquals("JyAjR2+]<3S`Hkf?i,0", music0.getGenre());
      assertEquals("", music0.getLyrics());
      assertEquals("", music0.getMusicalFigures());
      assertEquals("?KIafDq'(AZ(wv\"5b2", music0.getName());
      assertEquals(2390, music0.getDuration());
      assertEquals("", music0.getInterpreter());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Music music0 = new Music("^,`", "^,`", "?*E/v", "Sim", (String) null, "e][O8T<./y$]", "", (-1610), true);
      music0.play();
      int int0 = music0.getReproductions();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Music music0 = new Music("", "8Gm.@Po ccyYRs", "Nome: ", "[=Zj?4yy:=,E,F_(Aw?", "Y[mR5:0", ":|_@dHlV", "", 0, false);
      music0.setReproductions((-2870));
      int int0 = music0.getReproductions();
      assertEquals((-2870), int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Music music0 = new Music((String) null, "", (String) null, "", (String) null, "", (String) null, 0, false);
      String string0 = music0.getPublisher();
      assertEquals(0, music0.getDuration());
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Music music0 = new Music("-d5 |Is|PqF5s7X^w39", "-d5 |Is|PqF5s7X^w39", "-d5 |Is|PqF5s7X^w39", "", "", "-d5 |Is|PqF5s7X^w39", "org.Model.Music.Music", (-491), false);
      String string0 = music0.getPublisher();
      assertEquals("-d5 |Is|PqF5s7X^w39", music0.getInterpreter());
      assertEquals("-d5 |Is|PqF5s7X^w39", music0.getGenre());
      assertEquals((-491), music0.getDuration());
      assertEquals("-d5 |Is|PqF5s7X^w39", music0.getName());
      assertFalse(music0.isExplicit());
      assertEquals("org.Model.Music.Music", music0.getAlbum());
      assertEquals("", music0.getLyrics());
      assertEquals("", music0.getMusicalFigures());
      assertEquals("-d5 |Is|PqF5s7X^w39", string0);
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Music music0 = new Music((String) null, "", (String) null, "", (String) null, "", (String) null, 0, false);
      String string0 = music0.getName();
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getDuration());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Music music0 = new Music();
      music0.getName();
      assertEquals(0, music0.getDuration());
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Music music0 = new Music();
      music0.setMusicalFigures((String) null);
      music0.getMusicalFigures();
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getDuration());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Music music0 = new Music();
      music0.setMusicalFigures("e )Tuz1s_r4+^e");
      music0.getMusicalFigures();
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
      assertEquals(0, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Music music0 = new Music();
      music0.setLyrics((String) null);
      music0.getLyrics();
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
      assertEquals(0, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Music music0 = new Music();
      music0.getLyrics();
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getDuration());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Music music0 = new Music();
      music0.setInterpreter((String) null);
      music0.getInterpreter();
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getDuration());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Music music0 = new Music();
      music0.getInterpreter();
      assertEquals(0, music0.getReproductions());
      assertEquals(0, music0.getDuration());
      assertFalse(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Music music0 = new Music((String) null, "/T)ZN6EcG'cr9n$E", (String) null, "/T)ZN6EcG'cr9n$E", "/T)ZN6EcG'cr9n$E", (String) null, "Interprete: ", 1, false);
      String string0 = music0.getGenre();
      assertEquals("/T)ZN6EcG'cr9n$E", music0.getLyrics());
      assertEquals("Interprete: ", music0.getAlbum());
      assertEquals(0, music0.getReproductions());
      assertEquals("/T)ZN6EcG'cr9n$E", music0.getInterpreter());
      assertEquals(1, music0.getDuration());
      assertEquals("/T)ZN6EcG'cr9n$E", music0.getMusicalFigures());
      assertNull(string0);
      assertFalse(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Music music0 = new Music("{2<B[", "cy$$wh<", "", "", "", "{2<B[", "cy$$wh<", 0, true);
      String string0 = music0.getGenre();
      assertEquals(0, music0.getReproductions());
      assertEquals("cy$$wh<", music0.getAlbum());
      assertEquals("", music0.getMusicalFigures());
      assertEquals("{2<B[", string0);
      assertEquals("{2<B[", music0.getName());
      assertTrue(music0.isExplicit());
      assertEquals("", music0.getPublisher());
      assertEquals("cy$$wh<", music0.getInterpreter());
      assertEquals("", music0.getLyrics());
      assertEquals(0, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Music music0 = new Music("", "", (String) null, "", "", "", "", 897, true);
      int int0 = music0.getDuration();
      assertEquals(0, music0.getReproductions());
      assertTrue(music0.isExplicit());
      assertEquals(897, int0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, (String) null, "QM", (String) null, "QM", "01^XY?:]VO<,}}w", 0, true);
      assertEquals(0, music0.getDuration());
      
      music0.setDuration((-1));
      int int0 = music0.getDuration();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Music music0 = new Music("m<", "m<", "m<", "m<", "m<", "", "m<", 0, false);
      String string0 = music0.getAlbum();
      assertEquals("m<", music0.getMusicalFigures());
      assertEquals("m<", music0.getName());
      assertEquals("m<", music0.getLyrics());
      assertEquals(0, music0.getReproductions());
      assertEquals("m<", music0.getPublisher());
      assertEquals("", music0.getGenre());
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getDuration());
      assertEquals("m<", string0);
      assertEquals("m<", music0.getInterpreter());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Music music0 = new Music();
      music0.getAlbum();
      assertEquals(0, music0.getDuration());
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Music music0 = new Music("?KIafDq'(AZ(wv\"5b2", "", "?KIafDq'(AZ(wv\"5b2", "", "", "JyAjR2+]<3S`Hkf?i,0", (String) null, 2390, false);
      music0.play();
      music0.clone();
      assertEquals(1, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Music music0 = new Music();
      music0.setReproductions((-1));
      music0.clone();
      assertEquals((-1), music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Music music0 = new Music("", "", "", "", "", (String) null, (String) null, 137, true);
      Music music1 = music0.clone();
      assertTrue(music1.isExplicit());
      assertEquals(137, music1.getDuration());
      assertEquals(137, music0.getDuration());
      assertTrue(music1.equals((Object)music0));
      assertEquals(0, music1.getReproductions());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, (String) null, (String) null, "bm7?xBZ5;_", "bm7?xBZ5;_", (String) null, (-770), true);
      Music music1 = music0.clone();
      assertTrue(music1.isExplicit());
      assertEquals((-770), music1.getDuration());
      assertEquals(0, music1.getReproductions());
      assertEquals((-770), music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Music music0 = null;
      try {
        music0 = new Music((Music) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Music music0 = new Music("", "", "", "", "", (String) null, (String) null, 137, true);
      String string0 = music0.getMusicalFigures();
      assertNotNull(string0);
      assertEquals(137, music0.getDuration());
      assertTrue(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Music music0 = new Music("", (String) null, (String) null, "cyb<ToSTG4N98Wz8", (String) null, "", "", 1, true);
      String string0 = music0.getGenre();
      assertEquals("", string0);
      assertEquals(0, music0.getReproductions());
      assertEquals("cyb<ToSTG4N98Wz8", music0.getLyrics());
      assertTrue(music0.isExplicit());
      assertEquals("", music0.getName());
      assertEquals(1, music0.getDuration());
      assertEquals("", music0.getAlbum());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Music music0 = new Music("", "", (String) null, "", "", "", "", 897, true);
      Music music1 = new Music(music0);
      assertEquals(897, music0.getDuration());
      assertEquals(897, music1.getDuration());
      assertTrue(music1.isExplicit());
      assertTrue(music1.equals((Object)music0));
      assertEquals(0, music1.getReproductions());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Music music0 = new Music("", "", "", "", "", (String) null, (String) null, 137, true);
      int int0 = music0.getReproductions();
      assertTrue(music0.isExplicit());
      assertEquals(0, int0);
      assertEquals(137, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Music music0 = new Music("?KIafDq'(AZ(wv\"5b2", "", "?KIafDq'(AZ(wv\"5b2", "", "", "JyAjR2+]<3S`Hkf?i,0", (String) null, 2390, false);
      String string0 = music0.getAlbum();
      assertEquals("", music0.getInterpreter());
      assertEquals(2390, music0.getDuration());
      assertEquals(0, music0.getReproductions());
      assertEquals("?KIafDq'(AZ(wv\"5b2", music0.getPublisher());
      assertEquals("", music0.getMusicalFigures());
      assertNull(string0);
      assertEquals("?KIafDq'(AZ(wv\"5b2", music0.getName());
      assertEquals("JyAjR2+]<3S`Hkf?i,0", music0.getGenre());
      assertEquals("", music0.getLyrics());
      assertFalse(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Music music0 = new Music("-d5 |Is|PqF5s7X^w39", "-d5 |Is|PqF5s7X^w39", "-d5 |Is|PqF5s7X^w39", "", "", "-d5 |Is|PqF5s7X^w39", "org.Model.Music.Music", (-491), false);
      String string0 = music0.getName();
      assertEquals("-d5 |Is|PqF5s7X^w39", string0);
      assertEquals("-d5 |Is|PqF5s7X^w39", music0.getGenre());
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
      assertEquals("", music0.getMusicalFigures());
      assertEquals((-491), music0.getDuration());
      assertEquals("-d5 |Is|PqF5s7X^w39", music0.getInterpreter());
      assertEquals("org.Model.Music.Music", music0.getAlbum());
      assertEquals("", music0.getLyrics());
      assertEquals("-d5 |Is|PqF5s7X^w39", music0.getPublisher());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Music music0 = new Music("", "8Gm.@Po ccyYRs", "Nome: ", "[=Zj?4yy:=,E,F_(Aw?", "Y[mR5:0", ":|_@dHlV", "", 0, false);
      String string0 = music0.getLyrics();
      assertEquals("", music0.getAlbum());
      assertEquals("8Gm.@Po ccyYRs", music0.getInterpreter());
      assertEquals(0, music0.getReproductions());
      assertEquals("[=Zj?4yy:=,E,F_(Aw?", string0);
      assertEquals("Nome: ", music0.getPublisher());
      assertEquals(0, music0.getDuration());
      assertEquals("", music0.getName());
      assertEquals("Y[mR5:0", music0.getMusicalFigures());
      assertFalse(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Music music0 = new Music("", "", "", "Editora: ", "Editora: ", ":}Ws=i", "Letra: ", 948, true);
      boolean boolean0 = music0.isExplicit();
      assertEquals("", music0.getPublisher());
      assertTrue(boolean0);
      assertEquals("Editora: ", music0.getLyrics());
      assertEquals(":}Ws=i", music0.getGenre());
      assertEquals("Editora: ", music0.getMusicalFigures());
      assertEquals("", music0.getInterpreter());
      assertEquals("Letra: ", music0.getAlbum());
      assertEquals(948, music0.getDuration());
      assertEquals("", music0.getName());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Music music0 = new Music(":x)YmKg", "Album: ", "org.Model.Music.Music", "t.#w/.x{ oZ0", "t.#w/.x{ oZ0", "Album: ", "", 2852, false);
      String string0 = music0.getInterpreter();
      assertEquals("t.#w/.x{ oZ0", music0.getMusicalFigures());
      assertEquals(2852, music0.getDuration());
      assertEquals("Album: ", string0);
      assertEquals(0, music0.getReproductions());
      assertEquals(":x)YmKg", music0.getName());
      assertEquals("Album: ", music0.getGenre());
      assertEquals("", music0.getAlbum());
      assertFalse(music0.isExplicit());
      assertEquals("org.Model.Music.Music", music0.getPublisher());
      assertEquals("t.#w/.x{ oZ0", music0.getLyrics());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Music music0 = new Music("", "", "", "Editora: ", "Editora: ", ":}Ws=i", "Letra: ", 948, true);
      String string0 = music0.getPublisher();
      assertEquals("", string0);
      assertEquals("Editora: ", music0.getLyrics());
      assertEquals("", music0.getName());
      assertEquals(0, music0.getReproductions());
      assertTrue(music0.isExplicit());
      assertEquals(":}Ws=i", music0.getGenre());
      assertEquals("Editora: ", music0.getMusicalFigures());
      assertEquals("", music0.getInterpreter());
      assertEquals("Letra: ", music0.getAlbum());
      assertEquals(948, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, (String) null, "QM", (String) null, "QM", "01^XY?:]VO<,}}w", 0, true);
      int int0 = music0.getDuration();
      assertEquals(0, music0.getReproductions());
      assertEquals("QM", music0.getGenre());
      assertEquals("QM", music0.getLyrics());
      assertEquals("01^XY?:]VO<,}}w", music0.getAlbum());
      assertEquals(0, int0);
      assertTrue(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Music music0 = new Music();
      music0.setName((String) null);
      Music music1 = music0.clone();
      boolean boolean0 = music0.equals(music1);
      assertFalse(music1.isExplicit());
      assertEquals(0, music1.getReproductions());
      assertEquals(0, music1.getDuration());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Music music0 = new Music();
      boolean boolean0 = music0.equals("");
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
      assertEquals(0, music0.getDuration());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Music music0 = new Music();
      boolean boolean0 = music0.equals(music0);
      assertFalse(music0.isExplicit());
      assertTrue(boolean0);
      assertEquals(0, music0.getReproductions());
      assertEquals(0, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Music music0 = new Music();
      music0.setName((String) null);
      Music music1 = new Music();
      boolean boolean0 = music0.equals(music1);
      //  // Unstable assertion: assertEquals(0, music1.getReproductions());
      //  // Unstable assertion: assertFalse(music1.isExplicit());
      //  // Unstable assertion: assertTrue(music1.equals((Object)music0));
      //  // Unstable assertion: assertEquals(0, music1.getDuration());
      //  // Unstable assertion: assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Music music0 = new Music();
      String string0 = music0.toString();
      assertEquals("Nome: \nInterprete: \nEditora: \nLetra: \nLinhas Musicais: \nGenero Musical: \nAlbum: \nDuracao: 0\nReproducoes: 0\nExplicita: Nao\n", string0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Music music0 = new Music();
      assertFalse(music0.isExplicit());
      
      music0.setExplicit(true);
      music0.toString();
      assertTrue(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Music music0 = new Music();
      music0.setGenre((String) null);
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
      assertEquals(0, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Music music0 = new Music();
      music0.setAlbum("HE}:y.FK)Uy&d3^C|T&2");
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
      assertEquals(0, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Music music0 = new Music();
      music0.setPublisher("");
      assertEquals(0, music0.getDuration());
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Music music0 = new Music();
      Music music1 = music0.clone();
      boolean boolean0 = music1.equals(music0);
      assertFalse(music1.isExplicit());
      assertEquals(0, music1.getDuration());
      assertTrue(boolean0);
      assertEquals(0, music1.getReproductions());
  }
}
