/*
 * This file was automatically generated by EvoSuite
 * Thu May 14 19:30:11 GMT 2026
 */

package org.Model.Music;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.Model.Music.MusicMultimedia;
import org.junit.runner.RunWith;

public class MusicMultimedia_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      MusicMultimedia musicMultimedia0 = new MusicMultimedia();
      musicMultimedia0.setUrl((String) null);
      String string0 = musicMultimedia0.getUrl();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      MusicMultimedia musicMultimedia0 = new MusicMultimedia("D", "D", "D", "MusicaMultimedia{", "D", "D", "", (-1), true, "MusicaMultimedia{");
      String string0 = musicMultimedia0.getUrl();
      assertEquals("MusicaMultimedia{", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      MusicMultimedia musicMultimedia0 = new MusicMultimedia();
      musicMultimedia0.play();
      MusicMultimedia musicMultimedia1 = musicMultimedia0.clone();
      assertTrue(musicMultimedia1.equals((Object)musicMultimedia0));
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      MusicMultimedia musicMultimedia0 = new MusicMultimedia("w|P,7qZP+wnT{|7", "w|P,7qZP+wnT{|7", "w|P,7qZP+wnT{|7", "", "w|P,7qZP+wnT{|7", "w|P,7qZP+wnT{|7", "", (-3082), true, "uawu((.6fD13was");
      musicMultimedia0.setReproductions((-3473));
      MusicMultimedia musicMultimedia1 = musicMultimedia0.clone();
      assertTrue(musicMultimedia1.equals((Object)musicMultimedia0));
      assertEquals("uawu((.6fD13was", musicMultimedia1.getUrl());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      MusicMultimedia musicMultimedia0 = new MusicMultimedia((String) null, (String) null, "", (String) null, "", "FgkP{H!^E6;{F", "", 1, false, (String) null);
      MusicMultimedia musicMultimedia1 = musicMultimedia0.clone();
      assertFalse(musicMultimedia1.isExplicit());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      MusicMultimedia musicMultimedia0 = null;
      try {
        musicMultimedia0 = new MusicMultimedia((MusicMultimedia) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      MusicMultimedia musicMultimedia0 = new MusicMultimedia("D", "D", "D", "MusicaMultimedia{", "D", "D", "", (-1), true, "MusicaMultimedia{");
      MusicMultimedia musicMultimedia1 = new MusicMultimedia(musicMultimedia0);
      assertTrue(musicMultimedia1.equals((Object)musicMultimedia0));
      assertEquals("MusicaMultimedia{", musicMultimedia1.getUrl());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      MusicMultimedia musicMultimedia0 = new MusicMultimedia();
      String string0 = musicMultimedia0.getUrl();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      MusicMultimedia musicMultimedia0 = new MusicMultimedia();
      musicMultimedia0.setUrl((String) null);
      MusicMultimedia musicMultimedia1 = new MusicMultimedia();
      boolean boolean0 = musicMultimedia0.equals(musicMultimedia1);
      //  // Unstable assertion: assertTrue(musicMultimedia1.equals((Object)musicMultimedia0));
      //  // Unstable assertion: assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      MusicMultimedia musicMultimedia0 = new MusicMultimedia();
      MusicMultimedia musicMultimedia1 = new MusicMultimedia("AbtumQ\": ", "AbtumQ\": ", "AbtumQ\": ", "AbtumQ\": ", "AbtumQ\": ", "AbtumQ\": ", "AbtumQ\": ", 39, false, "AbtumQ\": ");
      boolean boolean0 = musicMultimedia0.equals(musicMultimedia1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MusicMultimedia musicMultimedia0 = new MusicMultimedia();
      boolean boolean0 = musicMultimedia0.equals(musicMultimedia0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      MusicMultimedia musicMultimedia0 = new MusicMultimedia();
      Object object0 = new Object();
      boolean boolean0 = musicMultimedia0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      MusicMultimedia musicMultimedia0 = new MusicMultimedia();
      String string0 = musicMultimedia0.toString();
      assertEquals("MusicaMultimedia{Nome: \nInterprete: \nEditora: \nLetra: \nLinhas Musicais: \nGenero Musical: \nAlbum: \nDuracao: 0\nReproducoes: 0\nExplicita: Nao\n, url=''}", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      MusicMultimedia musicMultimedia0 = new MusicMultimedia();
      musicMultimedia0.setUrl((String) null);
      MusicMultimedia musicMultimedia1 = musicMultimedia0.clone();
      boolean boolean0 = musicMultimedia0.equals(musicMultimedia1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      MusicMultimedia musicMultimedia0 = new MusicMultimedia();
      MusicMultimedia musicMultimedia1 = musicMultimedia0.clone();
      boolean boolean0 = musicMultimedia0.equals(musicMultimedia1);
      assertTrue(musicMultimedia1.equals((Object)musicMultimedia0));
      assertTrue(boolean0);
  }
}
