/*
 * This file was automatically generated by EvoSuite
 * Thu May 14 19:31:17 GMT 2026
 */

package org.Model.Music;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.LocalDate;
import org.Model.Music.Music;
import org.Model.Music.MusicReproduction;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.junit.runner.RunWith;

public class MusicReproduction_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Music music0 = new Music();
      music0.setExplicit(true);
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-1L));
      MusicReproduction musicReproduction0 = new MusicReproduction(music0, localDate0);
      Music music1 = musicReproduction0.getMusic();
      assertEquals("", music1.getMusicalFigures());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Music music0 = new Music();
      MusicReproduction musicReproduction0 = new MusicReproduction(music0);
      music0.play();
      Music music1 = musicReproduction0.getMusic();
      assertEquals("", music1.getInterpreter());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Music music0 = new Music("Ox^^[@nL\"}fU3F',", (String) null, "Album: ", "Album: ", "Ox^^[@nL\"}fU3F',", "TjnN548a@r%9", (String) null, 0, false);
      MusicReproduction musicReproduction0 = new MusicReproduction(music0);
      music0.setReproductions((-890));
      Music music1 = musicReproduction0.getMusic();
      assertEquals((-890), music1.getReproductions());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Music music0 = new Music("M;/0zf}x#7?%", "M;/0zf}x#7?%", "m.zKnA_}'ZSUR", "M;/0zf}x#7?%", "", "M;/0zf}x#7?%", "", (-1), false);
      MusicReproduction musicReproduction0 = new MusicReproduction(music0);
      Music music1 = musicReproduction0.getMusic();
      assertFalse(music1.isExplicit());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Music music0 = new Music();
      MusicReproduction musicReproduction0 = new MusicReproduction(music0, (LocalDate) null);
      LocalDate localDate0 = musicReproduction0.getDate();
      assertNull(localDate0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      MusicReproduction musicReproduction0 = null;
      try {
        musicReproduction0 = new MusicReproduction((MusicReproduction) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Music music0 = new Music("", "", "", "", "", "", "M#U", 1, false);
      LocalDate localDate0 = MockLocalDate.ofYearDay(1, 1);
      MusicReproduction musicReproduction0 = new MusicReproduction(music0, localDate0);
      Music music1 = musicReproduction0.getMusic();
      assertFalse(music1.isExplicit());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Music music0 = new Music("", "", "", "", "", "", "M#U", 1, false);
      LocalDate localDate0 = MockLocalDate.ofYearDay(1, 1);
      MusicReproduction musicReproduction0 = new MusicReproduction(music0, localDate0);
      MusicReproduction musicReproduction1 = new MusicReproduction(musicReproduction0);
      assertFalse(musicReproduction1.equals((Object)musicReproduction0));
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Music music0 = new Music("Ox^^[@nL\"}fU3F',", (String) null, "Album: ", "Album: ", "Ox^^[@nL\"}fU3F',", "TjnN548a@r%9", (String) null, 0, false);
      MusicReproduction musicReproduction0 = new MusicReproduction(music0);
      LocalDate localDate0 = musicReproduction0.getDate();
      assertNotNull(localDate0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Music music0 = new Music();
      LocalDate localDate0 = MockLocalDate.now();
      MusicReproduction musicReproduction0 = new MusicReproduction(music0, localDate0);
      musicReproduction0.setDate(localDate0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MusicReproduction musicReproduction0 = new MusicReproduction((Music) null);
      Music music0 = musicReproduction0.getMusic();
      assertNull(music0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Music music0 = new Music();
      LocalDate localDate0 = MockLocalDate.now();
      MusicReproduction musicReproduction0 = new MusicReproduction(music0, localDate0);
      musicReproduction0.setMusic(music0);
      assertEquals("", music0.getMusicalFigures());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Music music0 = new Music();
      LocalDate localDate0 = MockLocalDate.now();
      MusicReproduction musicReproduction0 = new MusicReproduction(music0, localDate0);
      MusicReproduction musicReproduction1 = musicReproduction0.clone();
      assertNotSame(musicReproduction0, musicReproduction1);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Music music0 = new Music();
      LocalDate localDate0 = MockLocalDate.now();
      MusicReproduction musicReproduction0 = new MusicReproduction(music0, localDate0);
      String string0 = musicReproduction0.toString();
      assertTrue(string0.contains("MusicReproduction{music =Nome: \nInterprete: \nEditora: \nLetra: \nLinhas Musicais: \nGenero Musical: \nAlbum: \nDuracao: 0\nReproducoes: 0\nExplicita: Nao\n,"));
  }
}
