/*
 * This file was automatically generated by EvoSuite
 * Thu May 14 19:35:53 GMT 2026
 */

package org.Model.Plan;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.Model.Plan.Plan;
import org.Model.Plan.PlanFree;
import org.Model.Plan.PlanPremiumBase;
import org.junit.runner.RunWith;

public class PlanPremiumBase_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = null;
      try {
        planPremiumBase0 = new PlanPremiumBase((Plan) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      String string0 = planPremiumBase0.getPlanName();
      assertEquals(0, planPremiumBase0.getPoints());
      assertEquals("PremiumBase", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PlanFree planFree0 = new PlanFree();
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase(planFree0);
      boolean boolean0 = planPremiumBase0.hasAccessToFavorites();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PlanFree planFree0 = new PlanFree();
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase(planFree0);
      boolean boolean0 = planPremiumBase0.canAccessLibrary();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      PlanFree planFree0 = new PlanFree();
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase(planFree0);
      planPremiumBase0.addPoints();
      assertEquals(10, planPremiumBase0.getPoints());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      PlanFree planFree0 = new PlanFree();
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase(planFree0);
      boolean boolean0 = planPremiumBase0.canChooseWhatToPlay();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      PlanFree planFree0 = new PlanFree();
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase(planFree0);
      boolean boolean0 = planPremiumBase0.canSkip();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      PlanFree planFree0 = new PlanFree();
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase(planFree0);
      String string0 = planPremiumBase0.toString();
      assertEquals("Plano: PremiumBase\n    Pontos: 0", string0);
  }
}
