/*
 * This file was automatically generated by EvoSuite
 * Thu May 14 19:36:58 GMT 2026
 */

package org.Model.Plan;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.Model.Plan.Plan;
import org.Model.Plan.PlanPremiumBase;
import org.Model.Plan.PlanPremiumTop;
import org.junit.runner.RunWith;

public class PlanPremiumTop_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PlanPremiumTop planPremiumTop0 = null;
      try {
        planPremiumTop0 = new PlanPremiumTop((Plan) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop(planPremiumBase0);
      boolean boolean0 = planPremiumTop0.hasAccessToFavorites();
      assertEquals(100, planPremiumTop0.getPoints());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop(planPremiumBase0);
      boolean boolean0 = planPremiumTop0.canChooseWhatToPlay();
      assertTrue(boolean0);
      assertEquals(100, planPremiumTop0.getPoints());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop(planPremiumBase0);
      String string0 = planPremiumTop0.getPlanName();
      assertEquals(100, planPremiumTop0.getPoints());
      assertEquals("PremiumTop", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop(planPremiumBase0);
      boolean boolean0 = planPremiumTop0.canAccessLibrary();
      assertTrue(boolean0);
      assertEquals(100, planPremiumTop0.getPoints());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop(planPremiumBase0);
      planPremiumTop0.addPoints();
      assertEquals(102, planPremiumTop0.getPoints());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop();
      String string0 = planPremiumTop0.toString();
      assertEquals("Plano: PremiumTop\n    Pontos: 0", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop(planPremiumBase0);
      boolean boolean0 = planPremiumTop0.canSkip();
      assertEquals(100, planPremiumTop0.getPoints());
      assertTrue(boolean0);
  }
}
