/*
 * This file was automatically generated by EvoSuite
 * Thu May 14 19:34:48 GMT 2026
 */

package org.Model.Plan;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.Model.Plan.Plan;
import org.Model.Plan.PlanFree;
import org.Model.Plan.PlanPremiumTop;
import org.junit.runner.RunWith;

public class PlanFree_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop();
      PlanFree planFree0 = new PlanFree(planPremiumTop0);
      planFree0.addPoints();
      assertEquals(5, planFree0.getPoints());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PlanFree planFree0 = new PlanFree();
      boolean boolean0 = planFree0.hasAccessToFavorites();
      assertFalse(boolean0);
      assertEquals(0, planFree0.getPoints());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop();
      PlanFree planFree0 = new PlanFree(planPremiumTop0);
      String string0 = planFree0.toString();
      assertEquals("Plano: Free\n    Pontos: 0", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PlanFree planFree0 = new PlanFree();
      boolean boolean0 = planFree0.canAccessLibrary();
      assertFalse(boolean0);
      assertEquals(0, planFree0.getPoints());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop();
      PlanFree planFree0 = new PlanFree(planPremiumTop0);
      boolean boolean0 = planFree0.canSkip();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop();
      PlanFree planFree0 = new PlanFree(planPremiumTop0);
      String string0 = planFree0.getPlanName();
      assertEquals("Free", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop();
      PlanFree planFree0 = new PlanFree(planPremiumTop0);
      boolean boolean0 = planFree0.canChooseWhatToPlay();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      PlanFree planFree0 = null;
      try {
        planFree0 = new PlanFree((Plan) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
