/*
 * This file was automatically generated by EvoSuite
 * Thu May 14 19:32:24 GMT 2026
 */

package org.Model.Album;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.Model.Album.Album;
import org.Model.Music.Music;
import org.junit.runner.RunWith;

public class Album_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Album album0 = new Album(">kNy\"nXc,Ue@#.?)nx=", ">kNy\"nXc,Ue@#.?)nx=");
      Music music0 = new Music();
      album0.removeMusic(music0);
      assertEquals(">kNy\"nXc,Ue@#.?)nx=", album0.getArtist());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Album album0 = new Album((String) null, "");
      String string0 = album0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Album album0 = new Album("", "org.Model.Album.Album");
      assertEquals("", album0.getName());
      
      album0.setName("org.Model.Album.Album");
      album0.getName();
      assertEquals("org.Model.Album.Album", album0.getArtist());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Album album0 = new Album("i", "i");
      Music music0 = new Music("i", "i", (String) null, "", "", "", (String) null, 1498, false);
      music0.play();
      album0.addMusic(music0);
      Music music1 = album0.getMusicByName("i");
      assertNull(music1.getPublisher());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Album album0 = new Album("Dt5K:,Ve192/F9", "BW(3cK~eLN'S");
      Music music0 = new Music();
      album0.addMusic(music0);
      music0.setReproductions((-2144834062));
      Music music1 = album0.getMusicByName("");
      assertEquals("BW(3cK~eLN'S", album0.getArtist());
      assertNotNull(music1);
      assertEquals("Dt5K:,Ve192/F9", album0.getName());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Album album0 = new Album("", "org.Model.Album.Album");
      Music music0 = new Music("", "org.Model.Album.Album", "", "org.Model.Album.Album", "org.Model.Album.Album", "#>1#oV#%ubC", "", 2095, true);
      album0.addMusic(music0);
      Music music1 = album0.getMusicByName("");
      assertEquals("org.Model.Album.Album", album0.getArtist());
      assertNotNull(music1);
      assertEquals("", album0.getName());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Album album0 = new Album("Dt5K:,Ve192/F9", "BW(3cK~eLN'S");
      Music music0 = new Music();
      music0.setDuration((-1994091956));
      album0.addMusic(music0);
      Music music1 = album0.getMusicByName("");
      assertEquals("Dt5K:,Ve192/F9", album0.getName());
      assertNotNull(music1);
      assertEquals("BW(3cK~eLN'S", album0.getArtist());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Album album0 = new Album("i9\"", (String) null);
      String string0 = album0.getArtist();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Album album0 = new Album("", "");
      String string0 = album0.getArtist();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.getMusics();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Album album0 = new Album("", "J\"_';k6u$i=Y");
      album0.addMusic((Music) null);
      // Undeclared exception!
      try { 
        album0.getMusicByName("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Album album0 = new Album();
      Music music0 = new Music();
      // Undeclared exception!
      try { 
        album0.addMusic(music0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Album album0 = new Album();
      Album album1 = null;
      try {
        album1 = new Album(album0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Album album0 = null;
      try {
        album0 = new Album((String) null, (String) null, (List<Music>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Album album0 = new Album("", "org.Model.Album.Album");
      Music music0 = new Music("", "org.Model.Album.Album", "", "org.Model.Album.Album", "org.Model.Album.Album", "#>1#oV#%ubC", "", 2095, true);
      album0.addMusic(music0);
      album0.getMusics();
      assertEquals("org.Model.Album.Album", album0.getArtist());
      assertEquals("", album0.getName());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Album album0 = new Album("", "org.Model.Album.Album");
      album0.getMusics();
      assertEquals("", album0.getName());
      assertEquals("org.Model.Album.Album", album0.getArtist());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Album album0 = new Album("", "org.Model.Album.Album");
      String string0 = album0.getName();
      assertEquals("org.Model.Album.Album", album0.getArtist());
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Album album0 = new Album("", "org.Model.Album.Album");
      String string0 = album0.getArtist();
      assertEquals("", album0.getName());
      assertEquals("org.Model.Album.Album", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("", "Editora: ", linkedList0);
      Album album1 = new Album(album0);
      assertEquals("Editora: ", album1.getArtist());
      assertEquals("", album1.getName());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Album album0 = new Album("U0h%tqH", "U0h%tqH");
      Music music0 = new Music("U0h%tqH", "Album: U-h%tqH\nArtista: U-h%tqH\nM\u00FAsicas:\n", "U0h%tqH", "U0h%tqH", "U0h%tqH", "Album: U0h%tqH\nArtista: U0h%tqH\nM\u00FAsicas:\n", "U0h%tqH", 0, false);
      album0.addMusic(music0);
      Music music1 = album0.getMusicByName("Album: U0h%tqH\nArtista: U0h%tqH\nM\u00FAsicas:\n");
      assertNull(music1);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Album album0 = new Album("U0h%tqH", "U0h%tqH");
      Music music0 = new Music("U0h%tqH", "Album: U-h%tqH\nArtista: U-h%tqH\nM\u00FAsicas:\n", "U0h%tqH", "U0h%tqH", "U0h%tqH", "Album: U0h%tqH\nArtista: U0h%tqH\nM\u00FAsicas:\n", "U0h%tqH", 0, false);
      album0.addMusic(music0);
      String string0 = album0.toString();
      assertEquals("Album: U0h%tqH\nArtista: U0h%tqH\nM\u00FAsicas:\nNome: U0h%tqH\nInterprete: Album: U-h%tqH\nArtista: U-h%tqH\nM\u00FAsicas:\n\nEditora: U0h%tqH\nLetra: U0h%tqH\nLinhas Musicais: U0h%tqH\nGenero Musical: Album: U0h%tqH\nArtista: U0h%tqH\nM\u00FAsicas:\n\nAlbum: U0h%tqH\nDuracao: 0\nReproducoes: 0\nExplicita: Nao\n\n", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Music music0 = new Music();
      linkedList0.add(music0);
      Album album0 = new Album("QrW", "QrW", linkedList0);
      assertEquals("QrW", album0.getArtist());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("", "Editora: ", linkedList0);
      album0.addMusic((Music) null);
      // Undeclared exception!
      try { 
        album0.clone();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("", "Editora: ", linkedList0);
      assertEquals("Editora: ", album0.getArtist());
      
      album0.setArtist("Editora: ");
      assertEquals("", album0.getName());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.removeMusic((Music) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("", "Editora: ", linkedList0);
      album0.setMusics(linkedList0);
      assertEquals("Editora: ", album0.getArtist());
      assertEquals("", album0.getName());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Album album0 = new Album("U0h%tqH", "U0h%tqH");
      Album album1 = album0.clone();
      assertEquals("U0h%tqH", album1.getArtist());
  }
}
