/*
 * This file was automatically generated by EvoSuite
 * Thu May 14 19:33:42 GMT 2026
 */

package org.Model.User;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.LocalDate;
import java.util.LinkedList;
import java.util.List;
import org.Model.Music.Music;
import org.Model.Music.MusicReproduction;
import org.Model.Plan.Plan;
import org.Model.Plan.PlanFree;
import org.Model.Plan.PlanPremiumBase;
import org.Model.Plan.PlanPremiumTop;
import org.Model.Playlist.Playlist;
import org.Model.User.User;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.junit.runner.RunWith;

public class User_ESTest {
  @org.junit.Before
  public void resetPlaylistCounter() throws Exception {
      java.lang.reflect.Field f = org.Model.Playlist.Playlist.class.getDeclaredField("idCounter");
      f.setAccessible(true);
      f.set(null, 0);
  }



  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String string0 = "~CK4I@-R0JK\\usax^r";
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop(planPremiumBase0);
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("\"@li4", "\"@li4", (String) null, string0, planPremiumTop0, linkedList0, linkedList1);
      Playlist playlist0 = new Playlist();
      user0.addPlaylistToLibrary(playlist0);
      Music music0 = new Music("gCyR5=E'[Tm?GT.8}", "Re'", "gCyR5=E'[Tm?GT.8}", "0zG*", "}", "v,{=|Q$|", "org.Model.Plan.PlanPremiumTop", 1491, true);
      try { 
        user0.removeMusicFromPlaylist(music0, (-1840700267));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: -1840700267
         //
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("xcca\"Xl_~", "j^DKL+Pz&lz%", "m  !R|`q^)", "m  !R|`q^)", planPremiumTop0, linkedList0, linkedList1);
      user0.addPlaylist("xcca\"Xl_~");
      try { 
        user0.getPlaylistById((-410));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: -410
         //
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      User user0 = new User("yv#1K9V@$_V7", "fLX", "yv#1K9V@$_V7", "fLX");
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop();
      user0.setPlan(planPremiumTop0);
      user0.addPlaylist("yv#1K9V@$_V7");
      Music music0 = new Music("{%rM2W:%", "9^n1.", "fLX", "{%rM2W:%", "9^n1.", "\";j\"D.4uC%p&;x=", "fLX", (-2088), false);
      try { 
        user0.addMusicPlaylist((-1), music0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: -1
         //
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      User user0 = new User();
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      user0.setPlan(planPremiumBase0);
      boolean boolean0 = user0.hasLibrary();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      User user0 = new User((String) null, "", "", (String) null);
      String string0 = user0.getUsername();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      User user0 = new User();
      List<MusicReproduction> list0 = user0.getMusicReproductions();
      User user1 = new User("S\u00F3 o autor da playlist pode adicionar m\u00FAsicas.", "S\u00F3 o autor da playlist pode adicionar m\u00FAsicas.", "S\u00F3 o autor da playlist pode adicionar m\u00FAsicas.", "NyFqh&<\"", planPremiumBase0, linkedList0, list0);
      String string0 = user1.getUsername();
      assertEquals("S\u00F3 o autor da playlist pode adicionar m\u00FAsicas.", string0);
      assertEquals("S\u00F3 o autor da playlist pode adicionar m\u00FAsicas.", user1.getAdress());
      assertEquals("NyFqh&<\"", user1.getPassword());
      assertEquals("S\u00F3 o autor da playlist pode adicionar m\u00FAsicas.", user1.getEmail());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String string0 = "~CK4I@-R0JK\\usax^r";
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop(planPremiumBase0);
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("\"@li4", "\"@li4", (String) null, string0, planPremiumTop0, linkedList0, linkedList1);
      Playlist playlist0 = new Playlist();
      playlist0.setId(1491);
      user0.addPlaylistToLibrary(playlist0);
      user0.getPlaylistById(1491);
      assertEquals("~CK4I@-R0JK\\usax^r", user0.getPassword());
      assertEquals("\"@li4", user0.getUsername());
      assertEquals("\"@li4", user0.getEmail());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      User user0 = new User(",Txs0U$&2(KG&1_9}", "yyx\"rGHg(pg25", "yyx\"rGHg(pg25", "\n  \uD83D\uDCE7 Email: ");
      user0.setPlan((Plan) null);
      user0.getPlan();
      assertEquals("yyx\"rGHg(pg25", user0.getEmail());
      assertEquals("yyx\"rGHg(pg25", user0.getAdress());
      assertEquals(",Txs0U$&2(KG&1_9}", user0.getUsername());
      assertEquals("\n  \uD83D\uDCE7 Email: ", user0.getPassword());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User(")cQ&j{M", "zcEqt^jA$)b2n?{LC", ")cQ&j{M", "Lck$p-.V", planPremiumBase0, linkedList0, linkedList1);
      planPremiumBase0.addPoints();
      user0.getPlan();
      assertEquals("zcEqt^jA$)b2n?{LC", user0.getEmail());
      assertEquals("Lck$p-.V", user0.getPassword());
      assertEquals(")cQ&j{M", user0.getAdress());
      assertEquals(")cQ&j{M", user0.getUsername());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      User user0 = new User();
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      planPremiumBase0.setPoints((-2164));
      user0.setPlan(planPremiumBase0);
      Plan plan0 = user0.getPlan();
      assertTrue(plan0.canChooseWhatToPlay());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      User user0 = new User(">w%Aqt lQH", ">w%Aqt lQH", ">w%Aqt lQH", ">w%Aqt lQH");
      user0.setPassword((String) null);
      String string0 = user0.getPassword();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      User user0 = new User("=ty~Skg*p%JtxI", "Utilizadores Free n\u00E3o possuem playlists.", "Utilizadores Free n\u00E3o possuem playlists.", "Utilizadores Free n\u00E3o possuem playlists.");
      String string0 = user0.getPassword();
      assertEquals("=ty~Skg*p%JtxI", user0.getUsername());
      assertEquals("Utilizadores Free n\u00E3o possuem playlists.", string0);
      assertEquals("Utilizadores Free n\u00E3o possuem playlists.", user0.getEmail());
      assertEquals("Utilizadores Free n\u00E3o possuem playlists.", user0.getAdress());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      User user0 = new User((String) null, (String) null, "$;.%2|r3}", ",U:v");
      String string0 = user0.getEmail();
      assertEquals(",U:v", user0.getPassword());
      assertNull(string0);
      assertEquals("$;.%2|r3}", user0.getAdress());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      User user0 = new User("nS)=)'T", "o*z@}SMY2Kd}'", "nS)=)'T", "nS)=)'T");
      String string0 = user0.getEmail();
      assertEquals("o*z@}SMY2Kd}'", string0);
      assertEquals("nS)=)'T", user0.getUsername());
      assertEquals("nS)=)'T", user0.getAdress());
      assertEquals("nS)=)'T", user0.getPassword());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop(planPremiumBase0);
      User user0 = new User("Q#oA", (String) null, "", (String) null);
      List<Playlist> list0 = user0.getPlaylists();
      LinkedList<MusicReproduction> linkedList0 = new LinkedList<MusicReproduction>();
      User user1 = new User((String) null, "Q#oA", (String) null, "(ih@.ZwpnPW", planPremiumTop0, list0, linkedList0);
      String string0 = user1.getAdress();
      assertNull(string0);
      assertEquals("Q#oA", user1.getEmail());
      assertEquals("Q#oA", user0.getUsername());
      assertEquals("(ih@.ZwpnPW", user1.getPassword());
      assertEquals("", user0.getAdress());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop();
      User user0 = new User();
      List<Playlist> list0 = user0.getPlaylists();
      List<MusicReproduction> list1 = user0.getMusicReproductions();
      User user1 = new User("org.Exceptions.NoPremissionException", "org.Exceptions.NoPremissionException", "org.Exceptions.NoPremissionException", "org.Exceptions.NoPremissionException", planPremiumTop0, list0, list1);
      String string0 = user1.getAdress();
      assertEquals("org.Exceptions.NoPremissionException", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      User user0 = new User((String) null, (String) null, "mL.8(jijnA:R@", (String) null);
      // Undeclared exception!
      try { 
        user0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      User user0 = new User();
      // Undeclared exception!
      try { 
        user0.setPlaylists((List<Playlist>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      User user0 = new User("F%Ywrrm~j", "org.Exceptions.NotFoundException", "", "L%>Yhi/mM~N");
      // Undeclared exception!
      try { 
        user0.setMusicReproductions((List<MusicReproduction>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      User user0 = new User();
      List<Playlist> list0 = user0.getPlaylists();
      List<MusicReproduction> list1 = user0.getMusicReproductions();
      User user1 = new User("u[z'iGyj", "i=t.rJVK:K", "", "i=t.rJVK:K", (Plan) null, list0, list1);
      // Undeclared exception!
      try { 
        user1.namePlaylists();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("", "", "", "DK.REgV)0V", (Plan) null, linkedList0, linkedList1);
      // Undeclared exception!
      try { 
        user0.hasLibrary();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop(planPremiumBase0);
      User user0 = new User("Q#oA", (String) null, "", (String) null);
      List<Playlist> list0 = user0.getPlaylists();
      LinkedList<MusicReproduction> linkedList0 = new LinkedList<MusicReproduction>();
      User user1 = new User((String) null, "Q#oA", (String) null, "(ih@.ZwpnPW", planPremiumTop0, list0, linkedList0);
      user1.addPlaylist("");
      // Undeclared exception!
      try { 
        user1.getUserPlaylistCount();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      User user0 = new User((String) null, "", "", "");
      user0.addPlaylistToLibrary((Playlist) null);
      // Undeclared exception!
      try { 
        user0.getPlaylists();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      User user0 = new User("\n", "\n", ".#DV]ws0+Y28Sth<s", "");
      user0.setPlan((Plan) null);
      // Undeclared exception!
      try { 
        user0.getPlaylistById((-3402));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      User user0 = new User();
      Music music0 = new Music("", "", "", "", "$0Z!>?W VM8XW%c%", "$0Z!>?W VM8XW%c%", "", 0, true);
      user0.addMusicReproduction(music0);
      // Undeclared exception!
      try { 
        user0.getMusicReproductionsCount((LocalDate) null, (LocalDate) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      linkedList1.add((MusicReproduction) null);
      User user0 = new User("0zG*", "N\u00E3o tem permiss\u00E3o para acede a este recurso: ", "0zG*", "0zG*", planPremiumBase0, linkedList0, linkedList1);
      // Undeclared exception!
      try { 
        user0.getMusicReproductions();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop(planPremiumBase0);
      User user0 = new User("Q#oA", (String) null, "", (String) null);
      List<Playlist> list0 = user0.getPlaylists();
      LinkedList<MusicReproduction> linkedList0 = new LinkedList<MusicReproduction>();
      User user1 = new User((String) null, "Q#oA", (String) null, "(ih@.ZwpnPW", planPremiumTop0, list0, linkedList0);
      // Undeclared exception!
      try { 
        user1.equals(user0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      User user0 = new User();
      user0.addPlaylistToLibrary((Playlist) null);
      // Undeclared exception!
      try { 
        user0.clone();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      User user0 = new User();
      user0.addPlaylistToLibrary((Playlist) null);
      // Undeclared exception!
      try { 
        user0.changePlaylistAutor((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      User user0 = new User("", "", "", "");
      user0.setPlan((Plan) null);
      // Undeclared exception!
      try { 
        user0.addPoints();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      User user0 = new User();
      Playlist playlist0 = new Playlist();
      user0.addPlaylistToLibrary(playlist0);
      try { 
        user0.addPlaylistToLibrary(playlist0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // J\u00E1 existe: 
         //
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      User user0 = new User("yv#1K9V@$_V7", "=&O", "yv#1K9V@$_V7", "=&O");
      user0.setPlan((Plan) null);
      // Undeclared exception!
      try { 
        user0.addPlaylist("yv#1K9V@$_V7");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      User user0 = new User("UwtyXF^Ta", "UwtyXF^Ta", "*@EB`Sg4n2lD6+", "\n  \uD83C\uDFE0 Morada: ");
      user0.addPlaylistToLibrary((Playlist) null);
      // Undeclared exception!
      try { 
        user0.addMusicPlaylist(0, (Music) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      User user0 = null;
      try {
        user0 = new User((User) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      LinkedList<MusicReproduction> linkedList0 = new LinkedList<MusicReproduction>();
      User user0 = null;
      try {
        user0 = new User("~<8A:C}Tp:P+F0w!8", "~<8A:C}Tp:P+F0w!8", "KU", "~<8A:C}Tp:P+F0w!8", (Plan) null, (List<Playlist>) null, linkedList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      LinkedList<Music> linkedList2 = new LinkedList<Music>();
      Playlist playlist0 = new Playlist("N\u00E3o tem permiss\u00E3o para aceder a este recurso: ", " [", linkedList2);
      linkedList0.add(playlist0);
      User user0 = new User("0zG*", "N\u00E3o tem permiss\u00E3o para aceder a este recurso: ", "0zG*", "0zG*", planPremiumBase0, linkedList0, linkedList1);
      user0.getPlaylists();
      assertEquals("0zG*", user0.getPassword());
      assertEquals("N\u00E3o tem permiss\u00E3o para aceder a este recurso: ", user0.getEmail());
      assertEquals("0zG*", user0.getUsername());
      assertEquals("0zG*", user0.getAdress());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      User user0 = new User((String) null, "", "", "");
      user0.addPlaylistToLibrary((Playlist) null);
      // Undeclared exception!
      try { 
        user0.addPlaylistToLibrary((Playlist) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      User user0 = new User();
      Playlist playlist0 = new Playlist();
      user0.addPlaylistToLibrary(playlist0);
      user0.changePlaylistAutor((String) null);
      Music music0 = new Music();
      // Undeclared exception!
      try { 
        user0.removeMusicFromPlaylist(music0, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      LinkedList<Music> linkedList2 = new LinkedList<Music>();
      Playlist playlist0 = new Playlist("N\u00E3o tem permiss\u00E3o para aceder a este recurso: ", " [", linkedList2);
      linkedList0.add(playlist0);
      User user0 = new User("0zG*", "N\u00E3o tem permiss\u00E3o para aceder a este recurso: ", "0zG*", "0zG*", planPremiumBase0, linkedList0, linkedList1);
      user0.changePlaylistAutor("\n  \uD83D\uDCE7 Email: ");
      assertEquals("0zG*", user0.getPassword());
      assertEquals("0zG*", user0.getUsername());
      assertEquals("0zG*", user0.getAdress());
      assertEquals("N\u00E3o tem permiss\u00E3o para aceder a este recurso: ", user0.getEmail());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      User user0 = new User("v0G;", "m#i)\"yQd", "Y&X)Zu1Pa5|B[Arim", "v0G;");
      List<MusicReproduction> list0 = user0.getMusicReproductions();
      User user1 = new User("%", "v0G;", "v0G;", "%", planPremiumBase0, linkedList0, list0);
      user1.addPlaylist("Y&X)Zu1Pa5|B[Arim");
      int int0 = user1.getUserPlaylistCount();
      assertEquals(1, int0);
      assertEquals("m#i)\"yQd", user0.getEmail());
      assertEquals("v0G;", user0.getPassword());
      assertEquals("%", user1.getUsername());
      assertEquals("v0G;", user1.getAdress());
      assertEquals("Y&X)Zu1Pa5|B[Arim", user0.getAdress());
      assertEquals("%", user1.getPassword());
      assertEquals("v0G;", user1.getEmail());
      assertEquals("v0G;", user0.getUsername());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      LinkedList<Music> linkedList2 = new LinkedList<Music>();
      Playlist playlist0 = new Playlist("N\u00E3o tem permiss\u00E3o para aceder a este recurso: ", " [", linkedList2);
      linkedList0.add(playlist0);
      User user0 = new User("0zG*", "N\u00E3o tem permiss\u00E3o para aceder a este recurso: ", "0zG*", "0zG*", planPremiumBase0, linkedList0, linkedList1);
      int int0 = user0.getUserPlaylistCount();
      assertEquals("0zG*", user0.getPassword());
      assertEquals("N\u00E3o tem permiss\u00E3o para aceder a este recurso: ", user0.getEmail());
      assertEquals("0zG*", user0.getUsername());
      assertEquals("0zG*", user0.getAdress());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("xcca\"Xl_~", "j^DKL+Pz&lz%", "m  !R|`q^)", "m  !R|`q^)", planPremiumTop0, linkedList0, linkedList1);
      user0.addPlaylist("xcca\"Xl_~");
      Music music0 = new Music("m  !R|`q^)", "j^DKL+Pz&lz%", "abK:", "abK:", "", "xcca\"Xl_~", "j^DKL+Pz&lz%", 0, true);
      try { 
        user0.removeMusicFromPlaylist(music0, 0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: m  !R|`q^)
         //
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      LinkedList<Music> linkedList2 = new LinkedList<Music>();
      Playlist playlist0 = new Playlist("N\u00E3o tem permiss\u00E3o para aceder a este recurso: ", " [", linkedList2);
      linkedList0.add(playlist0);
      User user0 = new User("0zG*", "N\u00E3o tem permiss\u00E3o para aceder a este recurso: ", "0zG*", "0zG*", planPremiumBase0, linkedList0, linkedList1);
      Music music0 = new Music("org.Model.User.User", "", "", " [", "N\u00E3o tem permiss\u00E3o para aceder a este recurso: ", "", "", 1900, true);
      try { 
        user0.removeMusicFromPlaylist(music0, 0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o tem permiss\u00E3o para aceder a este recurso: S\u00F3 o autor da playlist pode remover m\u00FAsicas.
         //
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      String string0 = "~CK4I@-R0JK\\usax^r";
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop(planPremiumBase0);
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("\"@li4", "\"@li4", (String) null, string0, planPremiumTop0, linkedList0, linkedList1);
      Playlist playlist0 = new Playlist();
      user0.addPlaylistToLibrary(playlist0);
      try { 
        user0.getPlaylistById(1491);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: 1491
         //
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      LinkedList<Music> linkedList2 = new LinkedList<Music>();
      Playlist playlist0 = new Playlist("N\u00E3o tem permiss\u00E3o para aceder a este recurso: ", " [", linkedList2);
      linkedList0.add(playlist0);
      User user0 = new User("0zG*", "N\u00E3o tem permiss\u00E3o para aceder a este recurso: ", "0zG*", "0zG*", planPremiumBase0, linkedList0, linkedList1);
      user0.getPlaylistById(0);
      assertEquals("N\u00E3o tem permiss\u00E3o para aceder a este recurso: ", user0.getEmail());
      assertEquals("0zG*", user0.getAdress());
      assertEquals("0zG*", user0.getUsername());
      assertEquals("0zG*", user0.getPassword());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      User user0 = new User("N\u00E3o encontrado: ", "", "e=rJN5&9", ", musicas=");
      // Undeclared exception!
      try { 
        user0.getPlaylistById((-1106));
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Utilizadores Free n\u00E3o podem adicionar m\u00FAsicas a playlists.
         //
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      LinkedList<Music> linkedList2 = new LinkedList<Music>();
      Playlist playlist0 = new Playlist("0zG*", "", linkedList2);
      linkedList0.add(playlist0);
      User user0 = new User("0zG*", "0zG*", "0zG*", "0zG*", planPremiumBase0, linkedList0, linkedList1);
      Music music0 = new Music("\n  \uD83D\uDCCB Plano: ", "", "", "", "0zG*", "", "", 1900, true);
      try { 
        user0.addMusicPlaylist(0, music0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o tem permiss\u00E3o para aceder a este recurso: S\u00F3 o autor da playlist pode adicionar m\u00FAsicas.
         //
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("xcca\"Xl_~", "j^DKL+Pz&lz%", "m  !R|`q^)", "m  !R|`q^)", planPremiumTop0, linkedList0, linkedList1);
      user0.addPlaylist("xcca\"Xl_~");
      Music music0 = new Music("m  !R|`q^)", "j^DKL+Pz&lz%", "abK:", "abK:", "", "xcca\"Xl_~", "j^DKL+Pz&lz%", 0, true);
      user0.addMusicPlaylist(0, music0);
      user0.removeMusicFromPlaylist(music0, 0);
      assertEquals("j^DKL+Pz&lz%", user0.getEmail());
      assertEquals("m  !R|`q^)", user0.getAdress());
      assertEquals("xcca\"Xl_~", user0.getUsername());
      assertEquals("m  !R|`q^)", user0.getPassword());
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      LinkedList<Music> linkedList2 = new LinkedList<Music>();
      Playlist playlist0 = new Playlist("N\u00E3o tem permiss\u00E3o para aceder a este recurso: ", "", linkedList2);
      linkedList0.add(playlist0);
      User user0 = new User("0zG*", "N\u00E3o tem permiss\u00E3o para aceder a este recurso: ", "0zG*", "0zG*", planPremiumBase0, linkedList0, linkedList1);
      Music music0 = new Music("\n  \uD83D\uDCCB Plano: ", "", "", "", "N\u00E3o tem permiss\u00E3o para aceder a este recurso: ", "", "", 1900, true);
      try { 
        user0.addMusicPlaylist(1900, music0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: 1900
         //
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      User user0 = new User();
      // Undeclared exception!
      try { 
        user0.addPlaylist("@:k&)Q");
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Utilizadores Free n\u00E3o podem adicionar playlists.
         //
      }
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop(planPremiumBase0);
      User user0 = new User("Q#oA", (String) null, "", (String) null);
      List<Playlist> list0 = user0.getPlaylists();
      LinkedList<MusicReproduction> linkedList0 = new LinkedList<MusicReproduction>();
      User user1 = new User((String) null, "Q#oA", (String) null, "(ih@.ZwpnPW", planPremiumTop0, list0, linkedList0);
      user1.addPlaylist("");
      String string0 = user1.namePlaylists();
      assertEquals("", user0.getAdress());
      assertEquals("Q#oA", user1.getEmail());
      assertEquals("(ih@.ZwpnPW", user1.getPassword());
      assertEquals("\uD83C\uDFB5 [#000]                           | Autor: null           \n", string0);
      assertEquals("Q#oA", user0.getUsername());
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop(planPremiumBase0);
      User user0 = new User("Q#oA", (String) null, "", (String) null);
      List<Playlist> list0 = user0.getPlaylists();
      LinkedList<MusicReproduction> linkedList0 = new LinkedList<MusicReproduction>();
      User user1 = new User((String) null, "Q#oA", (String) null, "(ih@.ZwpnPW", planPremiumTop0, list0, linkedList0);
      user1.namePlaylists();
      assertEquals("", user0.getAdress());
      assertEquals("(ih@.ZwpnPW", user1.getPassword());
      assertEquals("Q#oA", user0.getUsername());
      assertEquals("Q#oA", user1.getEmail());
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      User user0 = new User();
      // Undeclared exception!
      try { 
        user0.namePlaylists();
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Utilizadores Free n\u00E3o possuem playlists.
         //
      }
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      User user0 = new User();
      User user1 = new User(user0);
      boolean boolean0 = user1.equals(user0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      User user0 = new User();
      List<Playlist> list0 = user0.getPlaylists();
      List<MusicReproduction> list1 = user0.getMusicReproductions();
      User user1 = new User("i=t.rJVK:K", "u[z'iGyj", "i=t.rJVK:K", "i=t.rJVK:K", (Plan) null, list0, list1);
      boolean boolean0 = user0.equals(user1);
      assertEquals("u[z'iGyj", user1.getEmail());
      assertEquals("i=t.rJVK:K", user1.getPassword());
      assertFalse(boolean0);
      assertEquals("i=t.rJVK:K", user1.getAdress());
      assertEquals("i=t.rJVK:K", user1.getUsername());
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      PlanFree planFree0 = new PlanFree();
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop(planFree0);
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("", "Plano: Free\n    Pontos: ", "Plano: Free\n    Pontos: ", "Plano: Free\n    Pontos: ", planPremiumTop0, linkedList0, linkedList1);
      boolean boolean0 = user0.equals("0B:}t\"_>U;:dM6;03");
      assertEquals("Plano: Free\n    Pontos: ", user0.getPassword());
      assertFalse(boolean0);
      assertEquals("Plano: Free\n    Pontos: ", user0.getEmail());
      assertEquals("Plano: Free\n    Pontos: ", user0.getAdress());
      assertEquals("", user0.getUsername());
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      User user0 = new User();
      boolean boolean0 = user0.equals(user0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      User user0 = new User();
      List<Playlist> list0 = user0.getPlaylists();
      List<MusicReproduction> list1 = user0.getMusicReproductions();
      User user1 = new User("", "i=t.rJVK:K", "", "i=t.rJVK:K", (Plan) null, list0, list1);
      boolean boolean0 = user1.equals(user0);
      assertEquals("i=t.rJVK:K", user1.getEmail());
      assertEquals("", user1.getUsername());
      assertEquals("i=t.rJVK:K", user1.getPassword());
      assertEquals("", user1.getAdress());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      User user0 = new User();
      LinkedList<MusicReproduction> linkedList0 = new LinkedList<MusicReproduction>();
      Music music0 = new Music();
      MusicReproduction musicReproduction0 = new MusicReproduction(music0);
      linkedList0.add(musicReproduction0);
      user0.setMusicReproductions(linkedList0);
      assertEquals("", user0.getUsername());
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("0zG*", "N\u00E3o tem permiss\u00E3o para aceder a este recurso: ", "0zG*", "0zG*", planPremiumBase0, linkedList0, linkedList1);
      Music music0 = new Music("org.Model.User.User", "", "", " [", "N\u00E3o tem permiss\u00E3o para aceder a este recurso: ", "", "", 1900, true);
      user0.addMusicReproduction(music0);
      User user1 = user0.clone();
      assertEquals("0zG*", user1.getPassword());
      assertEquals("0zG*", user1.getAdress());
      assertEquals("0zG*", user1.getUsername());
      assertEquals("N\u00E3o tem permiss\u00E3o para aceder a este recurso: ", user1.getEmail());
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      User user0 = new User((String) null, (String) null, "7Y^P{`eDVi", (String) null);
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      Playlist playlist0 = new Playlist("MV", "Re'", (List<Music>) null);
      linkedList0.add(playlist0);
      user0.setPlaylists(linkedList0);
      assertTrue(linkedList0.contains(playlist0));
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      Music music0 = new Music(")cQ&j{M", "", (String) null, "s1oZc", "fQt$#\"", "Lck$p-.V", (String) null, 10, false);
      MusicReproduction musicReproduction0 = new MusicReproduction(music0);
      linkedList1.addFirst(musicReproduction0);
      User user0 = new User(")cQ&j{M", "zcEqt^jA$)b2n?{LC", ")cQ&j{M", "Lck$p-.V", planPremiumBase0, linkedList0, linkedList1);
      List<MusicReproduction> list0 = user0.getMusicReproductions();
      assertEquals(")cQ&j{M", user0.getAdress());
      assertEquals(")cQ&j{M", user0.getUsername());
      assertEquals(1, list0.size());
      assertEquals("zcEqt^jA$)b2n?{LC", user0.getEmail());
      assertEquals("Lck$p-.V", user0.getPassword());
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      User user0 = new User();
      user0.setEmail("FW[i\";Ex");
      assertEquals("", user0.getUsername());
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      User user0 = new User();
      String string0 = user0.getEmail();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("xcca\"Xl_~", "j^DKL+Pz&lz%", "m  !R|`q^)", "m  !R|`q^)", planPremiumTop0, linkedList0, linkedList1);
      assertEquals("m  !R|`q^)", user0.getAdress());
      
      user0.setAdress("");
      assertEquals("xcca\"Xl_~", user0.getUsername());
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      User user0 = new User("yv#1K9V@$_V7", "X", "yv#1K9V@$_V7", "X");
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop();
      user0.setPlan(planPremiumTop0);
      user0.addPlaylist("yv#1K9V@$_V7");
      Music music0 = new Music("{%rM2W:%", "9^n1.", "X", "{%rM2W:%", "9^n1.", "\";j\"D.4uC%p&;x=", "X", (-2088), false);
      try { 
        user0.removeMusicFromPlaylist(music0, 3205);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: 3205
         //
      }
  }



  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      User user0 = new User();
      String string0 = user0.getPassword();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      User user0 = new User("", "", "", "");
      LocalDate localDate0 = MockLocalDate.ofYearDay((-493), 10);
      int int0 = user0.getMusicReproductionsCount(localDate0, (LocalDate) null);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      User user0 = new User("", "", "", "");
      String string0 = user0.getUsername();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      User user0 = new User();
      boolean boolean0 = user0.hasLibrary();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      User user0 = new User();
      Plan plan0 = user0.getPlan();
      assertFalse(plan0.canChooseWhatToPlay());
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      User user0 = new User("", "", "", "");
      user0.setUsername("L_5");
      assertEquals("", user0.getEmail());
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      User user0 = new User("", "|ZsOcLdKE", "", "N\u00E3o encontrado: ");
      user0.addPoints();
      assertEquals("", user0.getUsername());
      assertEquals("", user0.getAdress());
      assertEquals("N\u00E3o encontrado: ", user0.getPassword());
      assertEquals("|ZsOcLdKE", user0.getEmail());
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      User user0 = new User();
      String string0 = user0.getAdress();
      assertEquals("", string0);
  }
}
