/*
 * This file was automatically generated by EvoSuite
 * Thu May 14 19:39:14 GMT 2026
 */

package org.Model.Playlist;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import org.Model.Music.Music;
import org.Model.Music.MusicReproduction;
import org.Model.Playlist.Playlist;
import org.Model.Playlist.PlaylistCreator;
import org.junit.runner.RunWith;

public class PlaylistCreator_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LinkedList<MusicReproduction> linkedList0 = new LinkedList<MusicReproduction>();
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      Music music0 = new Music("org.Model.Music.Music", "", "org.Model.Music.Music", "org.Model.Music.Music", (String) null, "org.Model.Music.Music", "org.Model.Music.Music", (-654), true);
      MusicReproduction musicReproduction0 = new MusicReproduction(music0);
      linkedList0.add(musicReproduction0);
      Music music1 = new Music("org.Model.Music.Music", "D_UMuv", "org.Model.Music.Music", "org.Model.Music.Music", "", "", "Zv1+D#2T09", 3, true);
      hashMap0.put("org.Model.Music.Music", music1);
      List<Music> list0 = PlaylistCreator.createFavoritesPlaylist(3, true, linkedList0, hashMap0);
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LinkedList<MusicReproduction> linkedList0 = new LinkedList<MusicReproduction>();
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      Music music0 = new Music("org.Model.Music.Music", "", "org.Model.Music.Music", "org.Model.Music.Music", (String) null, "org.Model.Music.Music", "org.Model.Music.Music", (-654), true);
      MusicReproduction musicReproduction0 = new MusicReproduction(music0);
      linkedList0.add(musicReproduction0);
      hashMap0.put("org.Model.Music.Music", music0);
      List<Music> list0 = PlaylistCreator.createFavoritesPlaylist(0, false, linkedList0, hashMap0);
      assertEquals(1, list0.size());
  }



  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      Music music0 = new Music();
      hashMap0.put("", music0);
      HashMap<Integer, Playlist> hashMap1 = new HashMap<Integer, Playlist>();
      List<Music> list0 = PlaylistCreator.createGenrePlaylist("Bf[", "Bf[", "", 2839, hashMap0, hashMap1);
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      Music music0 = new Music("", "", "", "", "J{{C~*llM0{Ji%Z", "", "", (-808), true);
      hashMap0.put("", music0);
      HashMap<Integer, Playlist> hashMap1 = new HashMap<Integer, Playlist>();
      List<Music> list0 = PlaylistCreator.createGenrePlaylist("J{{C~*llM0{Ji%Z", "", "", (-808), hashMap0, hashMap1);
      assertTrue(list0.contains(music0));
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      // Undeclared exception!
      try { 
        PlaylistCreator.createRandomPlaylist((Map<String, Music>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }



  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      HashMap<Integer, Playlist> hashMap0 = new HashMap<Integer, Playlist>();
      // Undeclared exception!
      try { 
        PlaylistCreator.createGenrePlaylist("n=/2uPn", "n=/2uPn", "n=/2uPn", (-154), (Map<String, Music>) null, hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      // Undeclared exception!
      try { 
        PlaylistCreator.createFavoritesPlaylist(2139, true, (List<MusicReproduction>) null, hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LinkedList<MusicReproduction> linkedList0 = new LinkedList<MusicReproduction>();
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      Music music0 = new Music("org.MoRe4.Music.Music", "org.MoRe4.Music.Music", "org.MoRe4.Music.Music", "org.MoRe4.Music.Music", "org.MoRe4.Music.Music", "org.MoRe4.Music.Music", "org.MoRe4.Music.Music", (-651), true);
      MusicReproduction musicReproduction0 = new MusicReproduction(music0);
      linkedList0.add(musicReproduction0);
      Music music1 = new Music("org.MoRe4.Music.Music", "org.MoRe4.Music.Music", "org.MoRe4.Music.Music", "org.MoRe4.Music.Music", "org.MoRe4.Music.Music", "org.MoRe4.Music.Music", "org.MoRe4.Music.Music", 3, true);
      hashMap0.put("org.MoRe4.Music.Music", music1);
      try { 
        PlaylistCreator.createFavoritesPlaylist(1, true, linkedList0, hashMap0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // N\u00E3o h\u00E1 m\u00FAsicas favoritas suficientes.
         //
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LinkedList<MusicReproduction> linkedList0 = new LinkedList<MusicReproduction>();
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      Music music0 = new Music("org.MoRe4.Music.Music", "org.MoRe4.Music.Music", "org.MoRe4.Music.Music", "org.MoRe4.Music.Music", "org.MoRe4.Music.Music", "org.MoRe4.Music.Music", "org.MoRe4.Music.Music", (-651), true);
      MusicReproduction musicReproduction0 = new MusicReproduction(music0);
      linkedList0.add(musicReproduction0);
      hashMap0.put("org.MoRe4.Music.Music", music0);
      List<Music> list0 = PlaylistCreator.createFavoritesPlaylist((-651), true, linkedList0, hashMap0);
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      LinkedList<MusicReproduction> linkedList0 = new LinkedList<MusicReproduction>();
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      Music music0 = new Music("org.MoRe4.Music.Music", "org.MoRe4.Music.Music", "org.MoRe4.Music.Music", "org.MoRe4.Music.Music", "org.MoRe4.Music.Music", "org.MoRe4.Music.Music", "org.MoRe4.Music.Music", (-651), true);
      MusicReproduction musicReproduction0 = new MusicReproduction(music0);
      linkedList0.add(musicReproduction0);
      hashMap0.put("org.MoRe4.Music.Music", music0);
      List<Music> list0 = PlaylistCreator.createFavoritesPlaylist(3, true, linkedList0, hashMap0);
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LinkedList<MusicReproduction> linkedList0 = new LinkedList<MusicReproduction>();
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      Music music0 = new Music("org.MoRe4.Music.Music", "org.MoRe4.Music.Music", "org.MoRe4.Music.Music", "org.MoRe4.Music.Music", "org.MoRe4.Music.Music", "org.MoRe4.Music.Music", "org.MoRe4.Music.Music", (-651), true);
      MusicReproduction musicReproduction0 = new MusicReproduction(music0);
      linkedList0.add(musicReproduction0);
      try { 
        PlaylistCreator.createFavoritesPlaylist(3, true, linkedList0, hashMap0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // N\u00E3o h\u00E1 m\u00FAsicas favoritas suficientes.
         //
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      Music music0 = new Music();
      LinkedList<MusicReproduction> linkedList0 = new LinkedList<MusicReproduction>();
      MusicReproduction musicReproduction0 = new MusicReproduction(music0);
      linkedList0.add(musicReproduction0);
      try { 
        PlaylistCreator.createFavoritesPlaylist(0, true, linkedList0, hashMap0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // N\u00E3o h\u00E1 m\u00FAsicas favoritas suficientes.
         //
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      Music music0 = new Music((String) null, (String) null, (String) null, (String) null, "6E1>r6h[u", "4E1>r6h[u", "4E1>r6h[u", 1, false);
      hashMap0.put("6E1>r6h[u", music0);
      HashMap<Integer, Playlist> hashMap1 = new HashMap<Integer, Playlist>();
      // Undeclared exception!
      try { 
        PlaylistCreator.createGenrePlaylist("6E1>r6h[u", (String) null, "6E1>r6h[u", 1, hashMap0, hashMap1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // N\u00E3o existem m\u00FAsicas desse g\u00E9nero.
         //
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      Music music0 = new Music();
      hashMap0.put("org.Model.Playlist.PlaylistCreator", music0);
      HashMap<Integer, Playlist> hashMap1 = new HashMap<Integer, Playlist>();
      try { 
        PlaylistCreator.createGenrePlaylist("org.Model.Playlist.PlaylistCreator", "org.Model.Playlist.PlaylistCreator", "", (-1637), hashMap0, hashMap1);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Playlist vazia.
         //
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      PlaylistCreator playlistCreator0 = new PlaylistCreator();
  }
}
