/*
 * This file was automatically generated by EvoSuite
 * Thu May 14 19:40:21 GMT 2026
 */

package org.Model.Playlist;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.Model.Music.Music;
import org.Model.Playlist.Playlist;
import org.Model.Playlist.PlaylistFavorites;
import org.Model.Playlist.PlaylistRandom;
import org.junit.runner.RunWith;

public class PlaylistFavorites_ESTest {
  @org.junit.Before
  public void resetPlaylistCounter() throws Exception {
      java.lang.reflect.Field f = org.Model.Playlist.Playlist.class.getDeclaredField("idCounter");
      f.setAccessible(true);
      f.set(null, 0);
  }



  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PlaylistFavorites playlistFavorites0 = new PlaylistFavorites();
      playlistFavorites0.setId(935);
      PlaylistRandom playlistRandom0 = playlistFavorites0.clone();
      assertEquals("", playlistRandom0.getAutor());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PlaylistFavorites playlistFavorites0 = new PlaylistFavorites((List<Music>) null);
      playlistFavorites0.setId((-413));
      PlaylistRandom playlistRandom0 = playlistFavorites0.clone();
      assertEquals("SpotifyUM", playlistRandom0.getAutor());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Playlist playlist0 = new Playlist("3x1cE7`F%cS8", "q.(h1_;3$bS");
      PlaylistFavorites playlistFavorites0 = new PlaylistFavorites(playlist0);
      playlistFavorites0.setName((String) null);
      PlaylistRandom playlistRandom0 = playlistFavorites0.clone();
      PlaylistFavorites playlistFavorites1 = new PlaylistFavorites(playlistRandom0);
      // Undeclared exception!
      try { 
        playlistFavorites0.equals(playlistFavorites1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PlaylistFavorites playlistFavorites0 = null;
      try {
        playlistFavorites0 = new PlaylistFavorites((Playlist) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Playlist playlist0 = new Playlist("3x1cE7`F%cS8", "q.(h1_;3$bS");
      PlaylistFavorites playlistFavorites0 = new PlaylistFavorites(playlist0);
      boolean boolean0 = playlistFavorites0.equals(playlistFavorites0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      PlaylistFavorites playlistFavorites0 = new PlaylistFavorites(linkedList0);
      boolean boolean0 = playlistFavorites0.equals(linkedList0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      PlaylistFavorites playlistFavorites0 = new PlaylistFavorites();
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      linkedList0.add((Music) null);
      playlistFavorites0.setMusics(linkedList0);
      // Undeclared exception!
      try { 
        playlistFavorites0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Playlist playlist0 = new Playlist("3x1cE7`F%cS8", "q.(h1_;3$bS");
      PlaylistFavorites playlistFavorites0 = new PlaylistFavorites(playlist0);
      String string0 = playlistFavorites0.toString();
      assertEquals("Playlist Favoritos{nome='3x1cE7`F%cS8', autor='q.(h1_;3$bS', musicas=[]}", string0);
  }
}
