/*
 * This file was automatically generated by EvoSuite
 * Thu May 14 19:41:29 GMT 2026
 */

package org.Model.Playlist;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.Model.Music.Music;
import org.Model.Playlist.Playlist;
import org.Model.Playlist.PlaylistRandom;
import org.junit.runner.RunWith;

public class PlaylistRandom_ESTest {
  @org.junit.Before
  public void resetPlaylistCounter() throws Exception {
      java.lang.reflect.Field f = org.Model.Playlist.Playlist.class.getDeclaredField("idCounter");
      f.setAccessible(true);
      f.set(null, 0);
  }



  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PlaylistRandom playlistRandom0 = new PlaylistRandom();
      List<Music> list0 = playlistRandom0.getMusics();
      PlaylistRandom playlistRandom1 = new PlaylistRandom("", list0);
      PlaylistRandom playlistRandom2 = playlistRandom1.clone();
      assertEquals("SpotifyUM", playlistRandom2.getAutor());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PlaylistRandom playlistRandom0 = new PlaylistRandom();
      playlistRandom0.setId((-1));
      PlaylistRandom playlistRandom1 = playlistRandom0.clone();
      assertNotSame(playlistRandom1, playlistRandom0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PlaylistRandom playlistRandom0 = new PlaylistRandom();
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      linkedList0.add((Music) null);
      playlistRandom0.setMusics(linkedList0);
      // Undeclared exception!
      try { 
        playlistRandom0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PlaylistRandom playlistRandom0 = null;
      try {
        playlistRandom0 = new PlaylistRandom((Playlist) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      PlaylistRandom playlistRandom0 = new PlaylistRandom((String) null, linkedList0);
      boolean boolean0 = playlistRandom0.equals(playlistRandom0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      PlaylistRandom playlistRandom0 = new PlaylistRandom((String) null, linkedList0);
      Object object0 = new Object();
      boolean boolean0 = playlistRandom0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      PlaylistRandom playlistRandom0 = new PlaylistRandom();
      PlaylistRandom playlistRandom1 = new PlaylistRandom(playlistRandom0);
      assertEquals("", playlistRandom1.getAutor());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      PlaylistRandom playlistRandom0 = new PlaylistRandom((String) null, linkedList0);
      PlaylistRandom playlistRandom1 = playlistRandom0.clone();
      // Undeclared exception!
      try { 
        playlistRandom1.equals(playlistRandom0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      PlaylistRandom playlistRandom0 = new PlaylistRandom((String) null, linkedList0);
      String string0 = playlistRandom0.toString();
      assertEquals("Playlist Aleat\u00F3ria{nome='null', autor='SpotifyUM', musicas=[]}", string0);
  }
}
