/*
 * This file was automatically generated by EvoSuite
 * Thu May 14 19:38:08 GMT 2026
 */

package org.Model.Playlist;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.Model.Music.Music;
import org.Model.Playlist.Playlist;
import org.junit.runner.RunWith;

public class Playlist_ESTest {
  @org.junit.Before
  public void resetPlaylistCounter() throws Exception {
      java.lang.reflect.Field f = org.Model.Playlist.Playlist.class.getDeclaredField("idCounter");
      f.setAccessible(true);
      f.set(null, 0);
  }



  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      // Undeclared exception!
      try { 
        playlist0.getMusicBYIndex(546);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // \u00CDndice fora dos limites da lista de m\u00FAsicas.
         //
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      Music music0 = new Music();
      playlist0.addMusic(music0);
      playlist0.removeMusic(music0);
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      playlist0.setName((String) null);
      playlist0.getName();
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Playlist playlist0 = new Playlist("", "\n");
      String string0 = playlist0.getName();
      assertEquals("\n", playlist0.getAutor());
      assertEquals("", string0);
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Playlist playlist0 = new Playlist("fGNK/sJ'W", "", linkedList0);
      playlist0.addMusic((Music) null);
      playlist0.getMusicBYIndex(0);
      assertEquals("fGNK/sJ'W", playlist0.getName());
      assertEquals("", playlist0.getAutor());
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Playlist playlist0 = new Playlist("J\u00E1 existe: ", "n$");
      Music music0 = new Music();
      music0.play();
      playlist0.addMusic(music0);
      playlist0.getMusicBYIndex(0);
      assertEquals(0, playlist0.getId());
      assertEquals("n$", playlist0.getAutor());
      assertEquals("J\u00E1 existe: ", playlist0.getName());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Playlist playlist0 = new Playlist("+la", "");
      Music music0 = new Music("+la", "", (String) null, "", "+la", "+la", "", 0, false);
      music0.setReproductions((-1));
      playlist0.addMusic(music0);
      playlist0.getMusicBYIndex(0);
      assertEquals(0, playlist0.getId());
      assertEquals("", playlist0.getAutor());
      assertEquals("+la", playlist0.getName());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      Music music0 = new Music("J)7,AaMn$<3NOW", "J)7,AaMn$<3NOW", "u4BIxRR`v` 7Dq", "u4BIxRR`v` 7Dq", "J)7,AaMn$<3NOW", "XvWC3CV?", "q`Hx9!8Z)48", 1094, false);
      playlist0.addMusic(music0);
      playlist0.getMusicBYIndex(0);
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      Music music0 = new Music("A?nyJS|B", "A?nyJS|B", "A?nyJS|B", "", "", (String) null, "A?nyJS|B", (-1359), true);
      playlist0.addMusic(music0);
      playlist0.getMusicBYIndex(0);
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Playlist playlist0 = new Playlist("nome='", "nome='");
      playlist0.setId(39);
      int int0 = playlist0.getId();
      assertEquals(39, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      playlist0.setId((-2674));
      int int0 = playlist0.getId();
      assertEquals((-2674), int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Playlist playlist0 = new Playlist((String) null, (String) null);
      playlist0.getAutor();
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      playlist0.getAutor();
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Playlist playlist0 = new Playlist("J\u00E1 existe: ", "n$");
      assertEquals("n$", playlist0.getAutor());
      assertEquals("J\u00E1 existe: ", playlist0.getName());
      
      Playlist playlist1 = new Playlist();
      Playlist playlist2 = playlist1.clone();
      assertEquals(1, playlist2.getId());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Playlist playlist0 = new Playlist("J\u00E1 existe: ", "n$");
      assertEquals(0, playlist0.getId());
      
      playlist0.setId((-1));
      playlist0.clone();
      assertEquals((-1), playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      // Undeclared exception!
      try { 
        playlist0.setMusics((List<Music>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Playlist playlist0 = new Playlist("", "");
      playlist0.addMusic((Music) null);
      // Undeclared exception!
      try { 
        playlist0.getMusics();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Playlist playlist0 = new Playlist((String) null, (String) null);
      Playlist playlist1 = new Playlist(playlist0);
      // Undeclared exception!
      try { 
        playlist0.equals(playlist1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      playlist0.addMusic((Music) null);
      // Undeclared exception!
      try { 
        playlist0.addMusic((Music) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Playlist playlist0 = null;
      try {
        playlist0 = new Playlist((Playlist) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Playlist playlist0 = new Playlist("J\u00E1 existe: ", "n$");
      int int0 = playlist0.getId();
      assertEquals("n$", playlist0.getAutor());
      assertEquals("J\u00E1 existe: ", playlist0.getName());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Playlist playlist0 = new Playlist("J\u00E1 existe: ", "n$");
      // Undeclared exception!
      try { 
        playlist0.getMusicBYIndex(0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // \u00CDndice fora dos limites da lista de m\u00FAsicas.
         //
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      // Undeclared exception!
      try { 
        playlist0.getMusicBYIndex((-2499));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // \u00CDndice fora dos limites da lista de m\u00FAsicas.
         //
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Playlist playlist0 = new Playlist("+la", "");
      Music music0 = new Music("+la", "", (String) null, "", "+la", "+la", "", 0, false);
      playlist0.addMusic(music0);
      try { 
        playlist0.addMusic(music0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // J\u00E1 existe: +la
         //
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Playlist playlist0 = new Playlist("Fb$fe=Cam", "Fb$fe=Cam");
      Playlist playlist1 = new Playlist(playlist0);
      assertTrue(playlist1.equals((Object)playlist0));
      
      playlist1.setAutor("KR&OR7L]qY");
      boolean boolean0 = playlist1.equals(playlist0);
      assertFalse(playlist1.equals((Object)playlist0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Playlist playlist0 = new Playlist("J\u00E1 existe: ", "n$");
      boolean boolean0 = playlist0.equals((Object) null);
      assertEquals(0, playlist0.getId());
      assertEquals("n$", playlist0.getAutor());
      assertFalse(boolean0);
      assertEquals("J\u00E1 existe: ", playlist0.getName());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Playlist playlist0 = new Playlist((String) null, (String) null);
      boolean boolean0 = playlist0.equals(playlist0);
      assertEquals(0, playlist0.getId());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Playlist playlist0 = new Playlist("J\u00E1 existe: ", "n$");
      Playlist playlist1 = new Playlist();
      boolean boolean0 = playlist0.equals(playlist1);
      assertFalse(boolean0);
      assertEquals("J\u00E1 existe: ", playlist0.getName());
      assertEquals("n$", playlist0.getAutor());
      assertEquals(1, playlist1.getId());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Playlist playlist0 = new Playlist("NPEd<K$<v[p", "NPEd<K$<v[p");
      Music music0 = new Music("NPEd<K$<v[p", "NPEd<K$<v[p", "NPEd<K$<v[p", "NPEd<K$<v[p", "NPEd<K$<v[p", "NPEd<K$<v[p", "NPEd<K$<v[p", 5644, false);
      playlist0.addMusic(music0);
      List<Music> list0 = playlist0.getMusics();
      playlist0.setMusics(list0);
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Playlist playlist0 = new Playlist((String) null, (String) null);
      List<Music> list0 = playlist0.getMusics();
      playlist0.setMusics(list0);
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Playlist playlist0 = new Playlist("Fbde=C8[as", "Fbde=C8[as");
      Music music0 = new Music();
      playlist0.addMusic(music0);
      List<Music> list0 = playlist0.getMusics();
      Playlist playlist1 = new Playlist("Fbde=C8[as", "Fbde=C8[as", list0);
      assertEquals(1, playlist1.getId());
      assertTrue(playlist1.equals((Object)playlist0));
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Playlist playlist0 = new Playlist("%{B+jN=@PcR0", "%{B+jN=@PcR0", (List<Music>) null);
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Playlist playlist0 = new Playlist("NPEd<K$<v[p", "NPEd<K$<v[p");
      playlist0.getName();
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      Playlist playlist1 = playlist0.clone();
      assertEquals(0, playlist1.getId());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      playlist0.removeMusic((Music) null);
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Playlist playlist0 = new Playlist("+la", "+la");
      playlist0.hashCode();
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Playlist playlist0 = new Playlist("+la", "+la");
      playlist0.getAutor();
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Playlist playlist0 = new Playlist("KR&OR7L]qY", "KR&OR7L]qY");
      Playlist playlist1 = new Playlist(playlist0);
      boolean boolean0 = playlist1.equals(playlist0);
      assertTrue(boolean0);
      assertEquals(0, playlist1.getId());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Playlist playlist0 = new Playlist("KR&OR7L]qY", "KR&OR7L]qY");
      String string0 = playlist0.toString();
      assertEquals(0, playlist0.getId());
      assertEquals("Playlist{nome='KR&OR7L]qY', autor='KR&OR7L]qY', musicas=[]}", string0);
  }
}
